export const REQUEST = 'REQUEST'
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'

export const createRequestTypes = base =>
  [REQUEST, SUCCESS, FAILURE].reduce((acc, type) => {
    acc[type] = `${base}_${type}`
    return acc
  }, {})

// Asynchroneous actions for saga
export const REMOVED_DOC_NAMED = createRequestTypes('REMOVED_DOC_NAMED')
export const LOADED_DOC_NAMED = createRequestTypes('LOADED_DOC_NAMED')
export const SAVED_DOC_NAMED = createRequestTypes('SAVED_DOC_NAMED')
export const LOADED_DOC_LIST = createRequestTypes('LOADED_DOC_LIST')

// Synchroneours actions
export const DID_NULL = 'DID_NULL'
export const MERGED_SELECTED_PROJECTS = 'MERGED_SELECTED_PROJECTS'
export const SELECTED_PROJECT_TO_MERGE = 'SELECTED_PROJECT_TO_MERGE'
export const UPDATED_NAMECOM_WIT_APPTOPTARGET = 'UPDATED_NAMECOM_WIT_APPTOPTARGET'
export const UPDATED_CONTENT_WIT_INSTANCE_MD = 'UPDATED_CONTENT_WIT_INSTANCE_MD'
export const UPDATED_CONTENT_WIT_INSTANCE = 'UPDATED_CONTENT_WIT_INSTANCE'
export const REMOVED_WIT_INSTANCES_FID_SUFFIX = 'REMOVED_WIT_INSTANCES_FID_SUFFIX'
export const CHANGED_WIT_INSTANCE_FID = 'CHANGED_WIT_INSTANCE_FID'
export const SIGNED_OUT_USER = 'SIGNED_OUT_USER'
export const REG_LOGIN_CHECK_USER = 'REG_LOGIN_CHECK_USER'
export const UPDATED_WIT_INSTANCE_BY_REACT_STATE = 'UPDATED_WIT_INSTANCE_BY_REACT_STATE'
export const ADDED_OVERWROTE_SET_WIT_INSTANCES = 'ADDED_OVERWROTE_SET_WIT_INSTANCES'
export const ALIGN_ZINDEXES_WIT_INSTANCES = 'ALIGN_ZINDEXES_WIT_INSTANCES'
export const UPDATED_CONTENT_WIT_INSTANCES = 'UPDATED_CONTENT_WIT_INSTANCES'
export const UPDATED_POS_WIT_INSTANCES = 'UPDATED_POS_WIT_INSTANCES'
export const REMOVED_FID_FROM_CID_OF_ANOTHER_FID = 'REMOVED_FID_FROM_CID_OF_ANOTHER_FID'
export const ADDED_FID_TO_CID_OF_ANOTHER_FID = 'ADDED_FID_TO_CID_OF_ANOTHER_FID'
export const REMOVED_CID = 'REMOVED_CID'
export const ADDED_CID = 'ADDED_CID'
export const REMOVED_WIT_INSTANCES = 'REMOVED_WIT_INSTANCES'
export const REMOVED_WIT_INSTANCE = 'REMOVED_WIT_INSTANCE'
export const ADDED_WIT_INSTANCE = 'ADDED_WIT_INSTANCE'
export const ADDED_WIT_TEMPLATE = 'ADDED_WIT_TEMPLATE'
export const SET_WIT_INSTANCE_FILTER = 'SET_WIT_INSTANCE_FILTER'
export const TOGGLED_LOADING_INDICATOR = 'TOGGLED_LOADING_INDICATOR'